# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assistantUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_assistantUi(object):
    def setupUi(self, assistantUi):
        assistantUi.setObjectName("assistantUi")
        assistantUi.resize(1584, 921)
        self.centralwidget = QtWidgets.QWidget(assistantUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 1601, 921))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("7LP8.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1182, 840, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1310, 840, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 40, 521, 141))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("T8bahf.gif"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 261, 71))
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(900, 50, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1180, 50, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1110, 550, 401, 171))
        self.label_4.setStyleSheet("border-radius:none;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("istockphoto-1178008276-170667a.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        assistantUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(assistantUi)
        QtCore.QMetaObject.connectSlotsByName(assistantUi)

    def retranslateUi(self, assistantUi):
        _translate = QtCore.QCoreApplication.translate
        assistantUi.setWindowTitle(_translate("assistantUi", "MainWindow"))
        self.pushButton.setText(_translate("assistantUi", "Run"))
        self.pushButton_2.setText(_translate("assistantUi", "Terminate"))
        self.label_3.setText(_translate("assistantUi", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    assistantUi = QtWidgets.QMainWindow()
    ui = Ui_assistantUi()
    ui.setupUi(assistantUi)
    assistantUi.show()
    sys.exit(app.exec_())
